spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
#  shell:
#    interactive:
#      enabled: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  main:
    allow-circular-references: true

logging:
  level:
    ROOT: ERROR